version: '3.5'

services:
  prestogres:
    ports:
      - 6689:8889
      # - 5679:5679
    build:
      context: ./
      dockerfile: prestogres.Dockerfile
      args:
        - PGDATA=/var/lib/postgresql/data
        - PRESTO_CATALOG=hive
        - PRESTO_SERVER=presto-basic-es.telefonicadev.com:8889
        - PRESTOGRES_VERSION=0.6.7
        - PROXY_PORT=5679
        - PROXY_SERVER=host.docker.internal

    cap_add:
      - NET_ADMIN

    networks:
      backend:

  # pgpool:
  #     image: bitnami/pgpool:4
  #     ports:
  #       - 5432:5432
  #     environment:
  #       - PGPOOL_BACKEND_NODES=0:prestogres:5439
  #       - PGPOOL_SR_CHECK_USER=customuser
  #       - PGPOOL_SR_CHECK_PASSWORD=custompassword
  #       - PGPOOL_ENABLE_LDAP=no
  #       - PGPOOL_POSTGRES_USERNAME=postgres
  #       - PGPOOL_POSTGRES_PASSWORD=adminpassword
  #       - PGPOOL_ADMIN_USERNAME=admin
  #       - PGPOOL_ADMIN_PASSWORD=adminpassword
  #     healthcheck:
  #       test: ["CMD", "/healthcheck.sh"]
  #       interval: 10s
  #       timeout: 5s
  #       retries: 5
  #     networks:
  #       backend:

volumes:
  db-data:

networks:
  backend:
    name: connexions
